/* home.vn2007@gmail.com - 2023 */

#pragma once

#define DRIVE_FRONT_LEFT_PORT 1
#define DRIVE_MIDDLE_LEFT_PORT 2
#define DRIVE_BACK_LEFT_PORT 3

#define DRIVE_FRONT_RIGHT_PORT 10
#define DRIVE_MIDDLE_RIGHT_PORT 9
#define DRIVE_BACK_RIGHT_PORT 8

#define IMU_PORT 7
#define ODOMETRY_X_PORT 8
